# Generator script: builds workflow.py
def w(s):
    with open('workflow.py', 'a') as f:
        f.write(s + '\n')

w('"""Workflow orchestration engine v2.0 — single source of truth."""')
w('import os')
w('')
w('DEV_PLAN_L = [')
w('    {"action":"skill","skill":"ponytail-audit","reason":"scan before design"},')
w('    {"action":"check_graphify","target":"GRAPH_REPORT.md","fallback":"suggest"},')
w('    {"action":"code_graph","tool":"code_graph_resolve","chain":"graphify->tokensave->Agent"},')
w('    {"action":"skill","skill":"research-deep","condition":"new tech/library/API"},')
w('    {"action":"skill","skill":"agent-reach","condition":"external lib/API"},')
w('    {"action":"mcp","tool":"patterns_list","reason":"known pitfalls"},')
w('    {"action":"enter_plan_mode"},')
w('    {"action":"skill","skill":"grill-me","condition":"L scale or tradeoffs"},')
w(']')
print('Done')

# Part 2: DEV build/review/harden/ship
w('')
w('DEV_PLAN_M = [')
w('    {"action":"skill","skill":"ponytail-audit"},')
w('    {"action":"code_graph","tool":"code_graph_resolve"},')
w('    {"action":"skill","skill":"research-deep","condition":"new tech"},')
w('    {"action":"skill","skill":"agent-reach","condition":"external lib/API"},')
w('    {"action":"mcp","tool":"patterns_list"},')
w('    {"action":"enter_plan_mode"},')
w(']')
w('DEV_PLAN_S = [')
w('    {"action":"verbal_plan","reason":"single file <50 lines"},')
w('    {"action":"mcp","tool":"patterns_list"},')
w(']')
w('DEV_BUILD = [')
w('    {"action":"rule","rule":"ponytail_6step"},')
w('    {"action":"skill","skill":"ui-ux-pro-max","condition":"UI work"},')
w('    {"action":"skill","skill":"superpowers:dispatching-parallel-agents","condition":"M/L"},')
w('    {"action":"tdd_or_manual"},')
w(']')
w('DEV_REVIEW = [')
w('    {"action":"skill","skill":"simplify"},')
w('    {"action":"skill","skill":"ponytail-review","reason":"diff over-engineering"},')
w('    {"action":"mcp","tool":"tokensave_impact"},')
w('    {"action":"skill","skill":"pensive:blast-radius"},')
w('    {"action":"skill","skill":"code-audit","condition":"M/L scale"},')
w(']')
w('DEV_HARDEN = [')
w('    {"action":"skill","skill":"pensive:harden","condition":"auth/payment/perms"},')
w('    {"action":"skill","skill":"pensive:performance-review","condition":"perf"},')
w('    {"action":"skill","skill":"conserve:unbloat","condition":"dead code"},')
w(']')
w('DEV_SHIP = [')
w('    {"action":"skill","skill":"commit-commands:commit-push-pr","condition":"M/L"},')
w('    {"action":"skill","skill":"commit-commands:commit","condition":"S"},')
w(']')

# Part 3: FIX
w('FIX_TRIAGE = [')
w('    {"action":"mcp","tool":"patterns_match","fallback":"skip->diagnose","rule":"NEVER block"},')
w('    {"action":"branch","high":"jump Phase4","low":"enter Phase1","known":"jump Phase3"},')
w(']')
w('FIX_DIAGNOSE = [')
w('    {"action":"skill","skill":"diagnose"},')
w('    {"action":"skill","skill":"superpowers:systematic-debugging","condition":"complex"},')
w('    {"action":"skill","skill":"grill-me","condition":"multi-hypothesis"},')
w(']')
w('FIX_REVIEW = [')
w('    {"action":"skill","skill":"simplify"},')
w('    {"action":"skill","skill":"ponytail-review"},')
w('    {"action":"mcp","tool":"tokensave_impact"},')
w('    {"action":"skill","skill":"pensive:blast-radius","condition":"multi-file"},')
w('    {"action":"skill","skill":"code-audit","reason":"similar issues"},')
w(']')

# Part 4: REFACTOR + START + CONTINUE + WRAP + AUDIT
w('REFACTOR_MEASURE = [')
w('    {"action":"skill","skill":"ponytail-audit","reason":"full-repo scan"},')
w('    {"action":"check_graphify"},')
w('    {"action":"code_graph","tool":"code_graph_resolve"},')
w('    {"action":"choose_metric"},')
w('    {"action":"record_baseline"},')
w(']')
w('REFACTOR_REVIEW = [')
w('    {"action":"verify_regression"},')
w('    {"action":"skill","skill":"pensive:blast-radius"},')
w('    {"action":"skill","skill":"simplify"},')
w('    {"action":"skill","skill":"ponytail-review"},')
w('    {"action":"check_ux","condition":"UI changes"},')
w('    {"action":"skill","skill":"pensive:unified-review","condition":"large"},')
w('    {"action":"verify_metrics"},')
w(']')
w('START = [')
w('    {"action":"locate_project"},')
w('    {"action":"detect_tech"},')
w('    {"action":"check_claude_mem"},')
w('    {"action":"mcp","tool":"session_read"},')
w('    {"action":"check_graphify","missing":"suggest"},')
w('    {"action":"read_claude_md"},')
w('    {"action":"git_status"},')
w('    {"action":"route","to":["dev","fix","refactor","code-audit"]},')
w(']')
w('CONTINUE_STEPS = [')
w('    {"action":"locate_project"},')
w('    {"action":"mcp","tool":"session_read"},')
w('    {"action":"check_claude_mem","offline":"skip"},')
w('    {"action":"read_claude_md"},')
w('    {"action":"git_status","what":"log+status+stash"},')
w('    {"action":"rebuild_context"},')
w('    {"action":"route"},')
w(']')
w('WRAP = [')
w('    {"action":"git_summary"},')
w('    {"action":"skill","skill":"ponytail-gain"},')
w('    {"action":"mcp","tool":"headroom_compress"},')
w('    {"action":"extract_lessons","skip_if":"trivial"},')
w('    {"action":"mcp","tool":"checklist_append"},')
w('    {"action":"mcp","tool":"patterns_append","condition":"novel bug"},')
w('    {"action":"mcp","tool":"session_cleanup"},')
w('    {"action":"suggest","done":"clean_gone","partial":"to-issues"},')
w(']')
w('AUDIT = [')
w('    {"action":"read_claude_md"},')
w('    {"action":"mcp","tool":"patterns_list"},')
w('    {"action":"skill","skill":"ponytail-debt"},')
w('    {"action":"read_memory","fallback":"skip"},')
w('    {"action":"read_reference","fallback":"skip"},')
w('    {"action":"scan","parallel":["patterns","ponytail","checklist"]},')
w('    {"action":"report"},')
w('    {"action":"fix_confirm"},')
w(']')

# Part 5: PHASE_MAP + HARD_RULES + functions
w('')
w('PHASE_MAP = {')
for k, v in [
    ('("dev","plan","L")', 'DEV_PLAN_L'), ('("dev","plan","M")', 'DEV_PLAN_M'),
    ('("dev","plan","S")', 'DEV_PLAN_S'), ('("dev","plan",None)', 'DEV_PLAN_S'),
    ('("dev","build",None)', 'DEV_BUILD'),
    ('("dev","verify",None)', '[{"action":"build_check","rule":"NO Review without build"}]'),
    ('("dev","review",None)', 'DEV_REVIEW'), ('("dev","harden",None)', 'DEV_HARDEN'),
    ('("dev","ship",None)', 'DEV_SHIP'),
    ('("fix","diagnose",None)', 'FIX_TRIAGE+FIX_DIAGNOSE'),
    ('("fix","plan",None)', '[{"action":"plan_simple_or_complex"}]'),
    ('("fix","baseline",None)', '[{"action":"build_check"}]'),
    ('("fix","fixing",None)', '[{"action":"tdd_or_manual","rule":"minimal"}]'),
    ('("fix","review",None)', 'FIX_REVIEW'),
    ('("fix","ship",None)', '[{"action":"skill","skill":"commit-commands:commit"}]'),
    ('("refactor","measure",None)', 'REFACTOR_MEASURE'),
    ('("refactor","plan",None)', '[{"action":"plan_simple_or_complex"}]'),
    ('("refactor","build",None)', '[{"action":"tdd_or_manual"}]'),
    ('("refactor","verify",None)', '[{"action":"build_check"}]'),
    ('("refactor","review",None)', 'REFACTOR_REVIEW'),
    ('("refactor","ship",None)', '[{"action":"skill","skill":"commit-commands:commit"}]'),
    ('("start","init",None)', 'START'),
    ('("continue","init",None)', 'CONTINUE_STEPS'),
    ('("wrap","init",None)', 'WRAP'),
    ('("code-audit","init",None)', 'AUDIT'),
]:
    w(f'    {k}: {v},')
w('}')
w('')
w('HARD_RULES = {')
w('    "no_review_without_build": "phase==review implies build_passed in checks",')
w('    "no_ship_without_build": "phase==ship implies build_passed in checks",')
w('    "no_graph_drop_to_grep": "graph->tokensave->Agent chain, NEVER Read+Grep",')
w('    "mcp_failure_not_blocking": "all MCP calls skip on failure, never retry",')
w('    "retry_limit_2": "same step retried 2x -> ask-teacher or handoff",')
w('}')
w('')
w('def step(slug, workflow, phase, scale=None, context=None):')
w('    ctx = context or {}')
w('    key = (workflow, phase, scale)')
w('    steps = PHASE_MAP.get(key) or PHASE_MAP.get((workflow, phase, None)) or []')
w('    def expand(obj):')
w('        if isinstance(obj, str): return obj.replace("${slug}",slug).replace("${task}",ctx.get("task",""))')
w('        if isinstance(obj, dict): return {k: expand(v) for k,v in obj.items()}')
w('        if isinstance(obj, list): return [expand(v) for v in obj]')
w('        return obj')
w('    return {"workflow":workflow,"phase":phase,"scale":scale,"total":len(steps),"steps":expand(steps)}')
w('')
w('def code_graph_resolve(slug, task, mode="explore"):')
w('    return {"tool":"code_graph_resolve","chain":[')
w('        {"p":1,"tool":"read","target":"graphify-out/GRAPH_REPORT.md","reason":"offline full-project graph"},')
w('        {"p":2,"tool":"tokensave_context","args":{"task":task,"mode":mode},"reason":"online code graph"},')
w('        {"p":3,"tool":"tokensave_search","args":{"query":task},"reason":"symbol search"},')
w('        {"p":4,"tool":"tokensave_dependencies","args":{"task":task},"reason":"dependency chain"},')
w('        {"p":5,"tool":"tokensave_similar","args":{"task":task},"reason":"similar code"},')
w('        {"p":6,"tool":"Agent","subagent_type":"Explore","reason":"last resort"},')
w('    ],"rule":"Each level only on empty. NEVER fall back to Read+Grep."}')
w('')
w('def validate_phase(wf, current, next_p, checks):')
w('    if next_p == "review" and not checks.get("build_passed"):')
w('        return False, "HARD_RULE: build_passed required for review"')
w('    if next_p == "ship" and not checks.get("build_passed"):')
w('        return False, "HARD_RULE: build_passed required for ship"')
w('    return True, None')
print('Full workflow.py built!')
